### ISSUE TITLE
Request to adopt this package

### ISSUE THREAD

**Issue by sylviamic** [nigeil/netctl-auto-gnome#1]
While old, this package is exactly what I've been looking to use on my own desktop. I'd love to adopt this and add support for netctl-auto. Mind if I branch this and send some commits your way? Or we can discuss moving the repository. In any case, great work!

**Comment by tjaartvdwalt** [comment]
Hi nigeil,
I am very excited that someone wants to use this package.Unfortunately I stopped using Gnome so I have no more use for the extension.

I will transfer ownership of this repo to you. If you have any questions I will be happy to provide assistance.

**Comment by tjaartvdwalt** [comment]
Oops I cannot do the transfer because your fork has the same name.
Would you mind renaming the forked repo, then I will transfer the original?

**Comment by sylviamic** [comment]
I've just renamed the package. Thanks for moving it over! I'll be sure you're listed as the original writer in the readme and related files. Quite a few changes have to be made to bring it up to snuff with Gnome 3.18, but I'm thinking most of your code can be reused.

**Comment by tjaartvdwalt** [comment]
Now I get the error:
`nigeil already has a repository in the tjaartvdwalt/netctl-gnome-shell-extension network`

If we can fix this, I will do the transfer, otherwise, I can put a note at the top of the README saying that development will continue on your fork.

**Comment by sylviamic** [comment]
Ah, that's another issue on my end. I've completely deleted my fork of your repository, and looking at the instructions provided by github, everything should now work just fine.
