### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by bertptrs** [nigeil/netctl-auto-gnome#6]
Currently, the project has no LICENSE or anything of that sort, which makes it difficult to distribute. Would you be so kind to choose a license (pretty much any will do) and add it to the repository?

**Comment by tjaartvdwalt** [comment]
Hi @bertptrs 

The code is released under GNU-GPL, which you can see  in the header in the [source file](https://github.com/nigeil/netctl-auto-gnome/blob/master/netctl-auto-gnome%40nigelmichki.ninja/extension.js).

It is probably a good idea to add a LICENSE file as well.

**Comment by bertptrs** [comment]
Ah okay, I did not check the source file. Thanks for the heads up! I modified my packaging script.

However, a LICENSE file would still be nice, as well as mentioning the license in the README.

**Comment by tjaartvdwalt** [comment]
Apparently I still have access to push to master :smiley: 
I added the LICENSE file
